import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  navbar: {
    backgroundColor: '#C4C4C4', 
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    marginTop: 50, 
  },
  navButton: {
    backgroundColor: '#000', 
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginHorizontal: 5, 
  },
  navButtonText: {
    color: '#fff', 
  },
  body: {
    flex: 1,
    backgroundColor: '#73779E', 
    padding: 20,
  },
  container: {
    flex: 1,
    backgroundColor: '#8A8FC3', 
    borderRadius: 10,
    padding: 10,
  },
  section: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 40,
    marginRight:10,
    marginLeft:5,
    backgroundColor: '#B2B9FF',
    borderRadius:10,
    width:360,
    height:160,
  },
  rectangle: {
    marginTop: 20,
    marginLeft: 10,
    marginRight: 10,
    width: 60,
    height:130,
    backgroundColor: 'black', 
  },

  section2: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    marginTop: 40,
    marginRight:10,
    marginLeft:5,
    backgroundColor: '#B2B9FF',
    borderRadius:10,
    width:360,
    height:160,
  },
  rectangle2: {
    marginTop: 10,
    marginBottom:10,
    marginLeft: 15,
    marginRight: 10,
    width: 330,
    height: 30,
    backgroundColor: 'black', 
  },
  section3: {
    flexDirection: 'column', 
    alignItems: 'center', 
    backgroundColor: '#B2B9FF',
    borderRadius:10,
    width:360,
    height:180,
    justifyContent: 'space-between',
    marginTop: 40,
    marginRight:10,
    marginLeft:5,
  },
  square: {
    marginTop: 10,
    marginBottom:10,
    marginLeft: 10,
    marginRight: 10,
    width: 40,
    height: 40,
    backgroundColor: '#000',
  },
  row: {
    flexDirection: 'row', 
  },
  footer: {
    backgroundColor: '#4E466A', 
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    padding: 50, 
    paddingBottom:30,
    paddingTop:30,
  },
  footerText: {
    color: '#DEDCE2', 
    fontSize: 18,
    fontWeight: 'bold',
    alignItems: 'center',
  },
});
